import app, { Component } from "apprun";
import { ui, Aext } from "./common-ui";
import { ColorTable } from "./colors";
import { compose, desktop, laptop, mobile, tablet, tokens } from "classy-ui";

const mediaUlClass = compose(
  tokens.display.FLEX,
  tokens.flexDirection.ROW,
  tokens.listStyleType.NONE,
  tokens.paddingLeft.SPACE_50,
  mobile(tokens.paddingLeft.SPACE_0)
);
const mediaLiClass = compose(
  tokens.borderStyle.SOLID,
  tokens.borderColor.GRAY_50,
  tokens.borderWidth.WIDTH_1,
  tokens.borderRadius.RADIUS_20,
  tokens.fontSize.SIZE_40,
  tokens.color.GRAY_40,
  tokens.marginRight.SPACE_10,
  tokens.paddingHorizontal.SPACE_20
);
/*
const mediaActive = compose(
  tokens.color.GREEN_80
);
TODO: Replace the four 'tokens.color.GREEN_80' below with a composition.
*/
const desktopClass = compose(
  mediaLiClass,
  desktop(tokens.color.GREEN_80)
);
const laptopClass = compose(
  mediaLiClass,
  laptop(tokens.color.GREEN_80)
);
const mobileClass = compose(
  mediaLiClass,
  mobile(tokens.color.GREEN_80)
);
const tabletClass = compose(
  mediaLiClass,
  tablet(tokens.color.GREEN_80)
);

export default class AboutComponent extends Component {
  state = { page: "Classy-UI" };

  view = (state) => {
    return <div class="classyuiinfo">
      <h1 class={ui.h1}>{state.page}</h1>
      <p><Aext href="https://classy-ui.io">Classy-UI</Aext> is CSS properties abstracted to design tokens. This abstraction does not only make your design consistent, but also discoverable and documented at your fingertips in the IDE, if your IDE has TypeScript Language Server support.</p>
      <p>Classy-UI is a <Aext href="https://babeljs.io">Babel</Aext>-plugin.</p>
      <h2 class={ui.h2}>Some features</h2>
      <ul>
        <li>Virtually no runtime in production</li>
        <li>The application can start without a mess of CSS files, just one generated by Classy-UI</li>
        <li>You completely get rid of specificity issues</li>
        <li>With an editor that has TypeScript Language Server support, you just select the tokens from the intellisense</li>
        <li>In production mode Classy-UI will shorten all the CSS classnames, group media queries and themes, creating a highly optimized bundle</li>
      </ul>
      
      <h2 class={ui.h2}>Just a few colors</h2>
      <p>Classy-UI was originally inspired by <Aext href="https://tailwindcss.com">Tailwindcss</Aext>, and therefore has a similar color palette. Tailwind’s background colors can be seen <Aext href="https://tailwindcss.com/docs/background-color/">over here</Aext>. Here is a small subset of the Classy-UI palette:</p>
      <ColorTable
        class={compose(tokens.marginLeft.SPACE_50, tokens.marginBottom.SPACE_60)} />
      
      <h2 class={ui.h2}>Media queries</h2>
      <p>Your current screen size class is indicated by dark green letters:</p>
      <ul class={mediaUlClass}>
        <li class={mobileClass}>mobile</li>
        <li class={tabletClass}>tablet</li>
        <li class={laptopClass}>laptop</li>
        <li class={desktopClass}>desktop</li>
      </ul>
      
      <p class={compose(tokens.utils.SCREEN_READER)}>This line shall only be presentet when a screenreader is used!</p>
    </div>
  }

  update = {
    "#Classy-UI": state => {
      return state;
    }
  }
}
